### ISSUE TITLE
TODO: 10월 12일 (목) 까지

### ISSUE THREAD

**Issue by winterjung** [Credium/backend#12]
- [x] `photo`컬럼 필요한 테이블에 넣기
- [x] `admin`페이지에 다른 모델 추가
- [x] 모델에 맞게 `views` 수정
- [x] 로그인 서버 띄우기
- [x] 모델 필드 명세서 프론트 쪽에 전달
